
@c %start of fragment

@node Xlib Rendering
@chapter Xlib Rendering
Rendering a pixbuf to an X drawable.

@section Overview
The gdk-pixbuf Xlib library provides several convenience functions to render
pixbufs to X drawables. It uses XlibRGB to render the image data.

These functions are analogous to those for the GDK version of gdk-pixbuf.

@section Usage
@include defuns-gdk-pixbuf-xlib-rendering.xml.texi

@c %end of fragment
