
@c %start of fragment

@node Cairo Interaction
@chapter Cairo Interaction
Functions to support using Cairo

@section Overview
Cairo is a graphics library that supports vector graphics and image compositing
that can be used with GDK. Since 2.8, GTK+ does most of its drawing using Cairo.

GDK does not wrap the Cairo API, instead it allows to create Cairo contexts
which can be used to draw on GDK drawables. Additional functions allow to
convert GDK's rectangles and regions into Cairo paths and to use pixbufs as
sources for drawing operations.

@section Usage
@include defuns-cairo_interaction.xml.texi

@c %end of fragment
