
@c %start of fragment

@node XlibRGB
@chapter XlibRGB
Rendering RGB buffers to X drawables.

@section Overview
The XlibRGB set of functions is a port of the @code{<gdk-rgb>} library to use
plain Xlib and X drawables. You can use these functions to render RGB buffers
into drawables very quickly with high-quality dithering.

@section Usage
@include defuns-gdk-pixbuf-xlib-rgb.xml.texi

@c %end of fragment
