
@c %start of fragment

@node AtkRelationSet
@chapter AtkRelationSet
A set of AtkRelations, normally the set of AtkRelations which an AtkObject has.

@section Overview
The AtkRelationSet held by an object establishes its relationships with objects
beyond the normal "parent/child" hierarchical relationships that all user
interface objects have. AtkRelationSets establish whether objects are labelled
or controlled by other components, share group membership with other components
(for instance within a radio-button group), or share content which "flows"
between them, among other types of possible relationships.

@section Usage
@include defuns-atkrelationset.xml.texi

@c %end of fragment
