
@c %start of fragment

@node AtkComponent
@chapter AtkComponent
The ATK interface provided by UI components which occupy a physical area on the
screen.

@section Overview
@code{<atk-component>} should be implemented by most if not all UI elements with
an actual on-screen presence, i.e. components which can be said to have a
screen-coordinate bounding box. Virtually all widgets will need to have
@code{<atk-component>} implementations provided for their corresponding
@code{<atk-object>} class. In short, only UI elements which are *not* GUI
elements will omit this ATK interface.

A possible exception might be textual information with a transparent background,
in which case text glyph bounding box information is provided by
@code{<atk-text>}.

@section Usage
@include defuns-atkcomponent.xml.texi

@c %end of fragment
