
@c %start of fragment

@node AtkGObjectAccessible
@chapter AtkGObjectAccessible
This object class is derived from AtkObject and can be used as a basis
implementing accessible objects.

@section Overview
This object class is derived from AtkObject. It can be used as a basis for
implementing accessible objects for GObjects which are not derived from
GtkWidget. One example of its use is in providing an accessible object for
GnomeCanvasItem in the GAIL library.

@section Usage
@include defuns-atkgobjectaccessible.xml.texi

@c %end of fragment
