
@c %start of fragment

@node AtkObject
@chapter AtkObject
The base object class for the Accessibility Toolkit API.

@section Overview
This class is the primary class for accessibility support via the Accessibility
ToolKit (ATK). Objects which are instances of @code{<atk-object>} (or instances
of AtkObject-derived types) are queried for properties which relate basic (and
generic) properties of a UI component such as name and description. Instances of
@code{<atk-object>} may also be queried as to whether they implement other ATK
interfaces (e.g. @code{<atk-action>}, @code{<atk-component>}, etc.), as
appropriate to the role which a given UI component plays in a user interface.

All UI components in an application which provide useful information or services
to the user must provide corresponding @code{<atk-object>} instances on request
(in GTK+, for instance, usually on a call to #@code{gtk-widget-get-accessible}),
either via ATK support built into the toolkit for the widget class or ancestor
class, or in the case of custom widgets, if the inherited @code{<atk-object>}
implementation is insufficient, via instances of a new @code{<atk-object>}
subclass.

@section Usage
@include defuns-atkobject.xml.texi

@c %end of fragment
