#!/bin/sh

this_dir=`dirname $0`
this_dir=`realpath $this_dir`

export GUILE_LOAD_PATH=$this_dir:$GUILE_LOAD_PATH
export LD_LIBRARY_PATH=$this_dir/gnome/gobject:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$this_dir/gnome/gtk:$LD_LIBRARY_PATH
export PKG_CONFIG_PATH=$this_dir:$PKG_CONFIG_PATH
export CFLAGS="-I$this_dir/gnome/gobject $CFLAGS"

# why do i need .libs here?
export LD_LIBRARY_PATH=$this_dir/gnome/corba/.libs:$LD_LIBRARY_PATH

exec "$@"
