#!/bin/sh

this_dir=`dirname $0`

export GUILE_LOAD_PATH=$this_dir:$GUILE_LOAD_PATH
export LD_LIBRARY_PATH=$this_dir/gnome/gobject:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$this_dir/gnome/gtk:$LD_LIBRARY_PATH

# why do i need .libs here?
export LD_LIBRARY_PATH=$this_dir/gnome/corba/.libs:$LD_LIBRARY_PATH

exec "$@"
