#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "usage: templatize PACKAGE-NAME"
    exit 1
fi

package=$1

echo "* setting up guile-gnome-$package--dev--0"
tla archive-setup guile-gnome-$package--dev--0

echo "* branching guile-gnome-$package--dev--0 from $(tla tree-version)"
tla tag `tla tree-version` guile-gnome-$package--dev--0

echo "* fetching guile-gnome-$package--dev--0 into ../$package"
cd ..
tla get guile-gnome-$package--dev--0 $package
cd $package

package_uc=$(echo $package | tr '[:lower:]-' '[:upper:]_')
package_un=$(echo $package | tr '-' '_')

for i in `tla inventory -s -f`; do
    echo "* templatizing $i"
    perl -i -p -e "s/_template/_${package_un}/g" $i
    perl -i -p -e "s/template_/${package_un}_/g" $i
    perl -i -p -e "s/template/$package/g" $i
    perl -i -p -e "s/TEMPLATE/$package_uc/g" $i
    if basename $i | grep -q template; then
        newname="$(dirname $i)/$(echo $(basename $i) | sed -e "s/template/$package/")"
        echo "* moving file $i to $newname"
        tla mv $i $newname
    fi
done

for i in `tla inventory -s -d`; do
    if echo $i | grep -q template; then
        newname=$(echo $i | sed -e "s/template/$package/")
        echo "* moving directory $i to $newname"
        mv $i $newname
    fi
done

echo "* removing templatize script"
tla rm templatize

