#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "usage: templatize PACKAGE-NAME"
    exit 1
fi

echo "* setting up guile-gnome-$1--dev--0"
tla archive-setup guile-gnome-$1--dev--0

echo "* branching guile-gnome-$1--dev--0 from $(tla tree-version)"
tla tag `tla tree-version` guile-gnome-$1--dev--0

echo "* fetching guile-gnome-$1--dev--0 into ../$1"
cd ..
tla get guile-gnome-$1--dev--0 $1
cd $1

for i in `tla inventory -s`; do
    echo "* templatizing $i"
    perl -i -p -e "s/template/$1/" $i
    if echo $i | grep -q template; then
        echo "* renaming $i to $(echo $i | sed -e \"s/template/$1\")"
        tla mv $i `echo $i | sed -e "s/template/$1/"`
    fi
done

echo "* removing templatize script"
tla rm templatize

