
@c %start of fragment

@node Truncating Files
@chapter Truncating Files
Force files to a particular length

@section Overview
Truncation of files is used to force them to a particular length. If a file
longer than specified, the trailing bytes are discarded, if it is shorter than
specified it is padded with zeros.

@section Usage
@include defuns-gnome-vfs-file-trunc-ops.xml.texi

@c %end of fragment
