
@c %start of fragment

@node Basic File Operations
@chapter Basic File Operations
Essential VFS operations. This includes creating, moving and deleting files,
opening and closing file handles.

@section Overview
GnomeVFS file operations are, for the most part, patterned after their POSIX
equivalents, with the systematic difference that they accept URIs rather than
paths on the local filesystem. This makes them easy to learn as if you are
already familiar with basic commands such as @code{open}, @code{seek},
@code{write}, etc you will feel right at home with GnomeVFS after learning a
little about URIs.

@section Usage
@include defuns-gnome-vfs-file-basic-ops.xml.texi

@c %end of fragment
