
@c %start of fragment

@node Strings
@chapter Strings
text buffers which grow automatically as text is added.

@section Overview
A @code{<g-string>} is similar to a standard C string, except that it grows
automatically as text is appended or inserted. Also, it stores the length of the
string, so can be used for binary data with embedded nul bytes.

@section Usage
@include defuns-strings.xml.texi

@c %end of fragment
