
@c %start of fragment

@node GdkDisplay
@chapter GdkDisplay
Controls the keyboard/mouse pointer grabs and a set of s

@section Overview
@code{<gdk-display>} objects purpose are two fold:

To grab/ungrab keyboard focus and mouse pointer

To manage and provide information about the @code{<gdk-screen>}(s) available for
this @code{<gdk-display>}

@code{<gdk-display>} objects are the GDK representation of the X Display which
can be described as @emph{a workstation consisting of a keyboard a pointing
device (such as a mouse) and one or more screens}. It is used to open and keep
track of various @code{<gdk-screen>} objects currently instanciated by the
application. It is also used to grab and release the keyboard and the mouse
pointer.

@section Usage
@include defuns-gdkdisplay.xml.texi

@c %end of fragment
