
@c %start of fragment

@node Animations
@chapter Animations
Animated images.

@section Overview
The gdk-pixbuf library provides a simple mechanism to load and represent
animations. An animation is conceptually a series of frames to be displayed over
time. Each frame is the same size. The animation may not be represented as a
series of frames internally; for example, it may be stored as a sprite and
instructions for moving the sprite around a background. To display an animation
you don't need to understand its representation, however; you just ask
gdk-pixbuf what should be displayed at a given point in time.

@section Usage
@include defuns-animation.xml.texi

@c %end of fragment
