
@c %start of fragment

@node Colormaps and Colors
@chapter Colormaps and Colors
Manipulation of colors and colormaps

@section Overview
These functions are used to modify colormaps. A colormap is an object that
contains the mapping between the color values stored in memory and the RGB
values that are used to display color values. In general, colormaps only contain
significant information for pseudo-color visuals, but even for other visual
types, a colormap object is required in some circumstances.

There are a couple of special colormaps that can be retrieved. The system
colormap (retrieved with @code{gdk-colormap-get-system}) is the default colormap
of the system. If you are using GdkRGB, there is another colormap that is
important - the colormap in which GdkRGB works, retrieved with
@code{gdk-rgb-get-cmap}. However, when using GdkRGB, it is not generally
necessary to allocate colors directly.

In previous revisions of this interface, a number of functions that take a
@code{<gdk-colormap>} parameter were replaced with functions whose names began
with "gdk_colormap_". This process will probably be extended somewhat in the
future - @code{gdk-color-white}, @code{gdk-color-black}, and
@code{gdk-color-change} will probably become aliases.

@section Usage
@include defuns-colors.xml.texi

@c %end of fragment
