
@c %start of fragment

@node gnome-triggers
@chapter gnome-triggers
Hierarchical signal mechanism for GNOME events.

@section Overview
The triggers API provides a way for applications to tell GNOME about interesting
events that then cause something to happen (for example, playing a sound). An
event can either be a function that is called, a sound that is played or an
external command that is run.

Each trigger can optionally have a associated with it and a . The is a list of
strings that help to classify the event, which imposes a hierarchy on the
trigger system. For example, messages about the hard drive partition /dev/hda1
may come under the section ("system", "device", "disk", "/dev/hda1"). This means
that an application could trigger all events for the ("system", "device")
sections and include those events, or be more specific and just trigger those
for ("system", "device", "disk", "/dev/hda1").

At the present time, triggers are not widely used in GNOME, being mostly used to
play sound events in response to certain actions.

@section Usage
@include defuns-gnome-triggers.xml.texi

@c %end of fragment
