
@c %start of fragment

@node gnome-score
@chapter gnome-score
Tracking best scores for games

@section Overview
The routines in this module provide a simple way to keep track of users' scores
in a game.

In order to acommodate file ownership permissions, the game application should
be installed setgid and the scoretable should only be writable by the group. The
program should call @code{gnome-score-init} as soon as possible inside the
@code{main} routine. This will open a pair of pipes to a child process which can
read and write the score table and then will drop the group privileges of the
main program back to the user's normal group id.

@section Usage
@include defuns-gnome-score.xml.texi

@c %end of fragment
