
@c %start of fragment

@node GnomeDruidPageEdge
@chapter GnomeDruidPageEdge
A widget used to implement first and last pages in a druid's sequence.

@section Overview
A druid can be thought of as having a page that starts the sequence, one or more
pages that end the sequences (there can be multiple end pages if the flow of
pages diverges at some point) and some pages that are in between the start and
end pages.

The @code{<gnome-druid-page-edge>} widget is for the first and last pages in a
druid's sequence of pages. Pages in the "middle" of a sequence should use
@code{<gnome-druid-page-standard>}.

@section Usage
@include defuns-gnome-druid-page-edge.xml.texi

@c %end of fragment
