
@c %start of fragment

@node AtkImage
@chapter AtkImage
The ATK Interface implemented by components which expose image or pixmap content
on-screen.

@section Overview
@code{<atk-image>} should be implemented by @code{<atk-object>} subtypes on
behalf of components which display image/pixmap information onscreen, and which
provide information (other than just widget borders, etc.) via that image
content. For instance, icons, buttons with icons, toolbar elements, and image
viewing panes typically should implement @code{<atk-image>}.

@code{<atk-image>} primarily provides two types of information: coordinate
information (useful for screen review mode of screenreaders, and for use by
onscreen magnifiers), and descriptive information. The descriptive information
is provided for alternative, text-only presentation of the most significant
information present in the image.

@section Usage
@include defuns-atkimage.xml.texi

@c %end of fragment
