
@c %start of fragment

@node Reading and Writing Files
@chapter Reading and Writing Files
Reading from and writing to open file handles.

@section Overview
Reading and writing operations are explained, also @code{gnome-vfs-seek}, which
is used to move the file pointer inside the file.

@section Usage
@include defuns-gnome-vfs-file-rw-ops.xml.texi

@c %end of fragment
