
@c %start of fragment

@node gnome-util
@chapter gnome-util
Miscellaneous utility functions.

@section Overview
The functions in this section provide some shortcuts to finding certain file
paths. There are also some functions for manipulating environment variables for
those systems that do not have @code{@code{getenv}} and similar functions.

Many of the function in here are now deprecated in favour of similar functions
in glib. The preferred replacement function in those cases is indicated below.

@section Usage
@include defuns-gnome-util.xml.texi

@c %end of fragment
