
@c %start of fragment

@node AtkRegistry
@chapter AtkRegistry
An object used to store the GType of the factories used to create an accessible
object for an object of a particular GType.

@section Overview
The AtkRegistry is normally used to create appropriate ATK "peers" for user
interface components. Application developers usually need only interact with the
AtkRegistry by associating appropriate ATK implementation classes with GObject
classes via the atk_registry_set_factory_type call, passing the appropriate
GType for application custom widget classes.

@section Usage
@include defuns-atkregistry.xml.texi

@c %end of fragment
