
@c %start of fragment

@node AtkRelation
@chapter AtkRelation
An object used to describe a relation between a object and one or more other
objects.

@section Overview
An AtkRelation describes a relation between an object and one or more other
objects. The actual relations that an object has with other objects are defined
as an AtkRelationSet, which is a set of AtkRelations.

@section Usage
@include defuns-atkrelation.xml.texi

@c %end of fragment
