
@c %start of fragment

@node AtkHypertext
@chapter AtkHypertext
The ATK interface which provides standard mechanism for manipulating hyperlinks.

@section Overview
An interface used for objects which implement linking between multiple resource
or content locations, or multiple 'markers' within a single document. A
Hypertext instance is associated with one or more Hyperlinks, which are
associated with particular offsets within the Hypertext's included content.
While this interface is derived from Text, there is no requirement that
Hypertext instances have textual content; they may implement Image as well, and
Hyperlinks need not have non-zero text offsets.

@section Usage
@include defuns-atkhypertext.xml.texi

@c %end of fragment
