
@c %start of fragment

@node Base64 Encoding
@chapter Base64 Encoding: encodes and decodes data in Base64 format
@section Overview
Base64 is an encoding that allows to encode a sequence of arbitrary bytes as a
sequence of printable ASCII characters. For the definition of Base64, see
@uref{http://www.ietf.org/rfc/rfc1421.txt,RFC 1421} or
@uref{http://www.ietf.org/rfc/rfc2045.txt,RFC 2045}. Base64 is most commonly
used as a MIME transfer encoding for email.

GLib supports incremental encoding using @code{g-base64-encode-step} and
@code{g-base64-encode-close}. Incremental decoding can be done with
@code{g-base64-decode-step}. To encode or decode data in one go, use
@code{g-base64-encode} or @code{g-base64-decode}.

Support for Base64 encoding has been added in GLib 2.12.

@section Usage
@include defuns-base64.xml.texi

@c %end of fragment
