
@c %start of fragment

@node GnomeCanvasEllipse
@chapter GnomeCanvasEllipse
Canvas item for drawing ellipses and circles

@section Overview
A canvas item for drawing ellipses and circles. The parameters are defined in
the parent classes including @code{<gnome-canvas-re>} which is shared with
@code{<gnome-canvas-rect>} items as well.

@section Usage
@include defuns-gnome-canvas-ellipse.xml.texi

@c %end of fragment
