
@c %start of fragment

@node Unified network I/O
@chapter Unified network I/O
Posix style network input/output functions.

@section Overview
The GnomeVFSSocket function family unifies network I/O through functions similar
to the standard POSIX read/write functions. The main difference is that all
operations are cancellable through the standard GnomeVFS cancellation mechanism
and you can specify a maximum amount of time an operation may take through
@code{<gnome-vfs-socket-set-timeout>}.

@section Usage
@include defuns-gnome-vfs-socket.xml.texi

@c %end of fragment
