
@c %start of fragment

@node GnomeDruidPageStandard
@chapter GnomeDruidPageStandard
A widget used to implement the middle pages in a druid's sequence.

@section Overview
This widget provides similar functionality to that in
@code{<gnome-druid-page-edge>}. It is used for pages that are not the initial or
terminal pages of a druid.

The main difference between an edge and a standard druid page (in a display
sense) is that standard pages do not have a left-side watermark and the body of
the contents section is a bit more arbitrary (it is a GTK+ vbox widget), rather
than just displaying text (which is the common case for edge pages).

There are some differences in the programming API between
@code{<gnome-druid-edge-page>} and @code{<gnome-druid-standard-page>} in GNOME 2
because the latter has been heavily redesigned internally, whereas the former
has not been. Later versions of GNOME (2.2 and beyond) may contain further
refinements to edge pages).

@section Usage
@include defuns-gnome-druid-page-standard.xml.texi

@c %end of fragment
