
@c %start of fragment

@node AtkHyperlink
@chapter AtkHyperlink
An ATK object which encapsulates a link or set of links in a hypertext document.

@section Overview
An ATK object which encapsulates a link or set of links (for instance in the
case of client-side image maps) in a hypertext document. It may implement the
AtkAction interface. AtkHyperlink may also be used to refer to inline embedded
content, since it allows specification of a start and end offset within the host
AtkHypertext object.

@section Usage
@include defuns-atkhyperlink.xml.texi

@c %end of fragment
