
@c %start of fragment

@node gnome-exec
@chapter gnome-exec
Execution of programs from within GNOME applications.

@section Overview
The gnome-execute family of functions are provided to simplify execution of
programs from withing GNOME applications. These routines are required to avoid
passing opened file descriptors to a child process (like the X11 sockets and
CORBA sockets). They will also make sure to terminate properly.

The range of possibilities goes from the most simple use to the most specialized
ones.

@section Usage
@include defuns-gnome-exec.xml.texi

@c %end of fragment
