
@c %start of fragment

@node Unified bufferd network I/O
@chapter Unified bufferd network I/O
Posix style buffered network input/output.

@section Overview
The GnomeVFSSocketBuffer functions are very similar to the GnomeVFSSocket ones.
The only difference is that all input/output is done through an internally
managed buffer. This might increase I/O performance as well as give you the
possibility to use some convenient functions like
@code{<gnome-vfs-socket-buffer-peekc>} and
@code{<gnome-vfs-socket-buffer-read-until>}. You can manually force all
internally buffered data to get written with
@code{<gnome-vfs-socket-buffer-flush>}.

@section Usage
@include defuns-gnome-vfs-socket-buffer.xml.texi

@c %end of fragment
