
@c %start of fragment

@node GnomeAppBar
@chapter GnomeAppBar
An application status and progress bar widget

@section Overview
A @code{<gnome-app-bar>} widget sits (usually) at the bottom of an application
window and contains a progress bar (for indicating time consuming tasks and
their completion status) and/or a status bar for sending short one-line message
to the user. It is also possible (in theory) for the user to edit the contents
of the status bar, should the application developer choose to allow that,
however @emph{note that this is not really working} in the present
implementation, so developers are recommended to avoid using interactive status
bars and use proper editable widgets instead.

@section Usage
@include defuns-gnome-appbar.xml.texi

@c %end of fragment
