
@c %start of fragment

@node gnome-app-helper
@chapter gnome-app-helper
Useful functions for populating menus and toolbars.

@section Overview
This module lets a developer easily create menus and toolbars for use in their
applications. Basically, a hierarchy of @code{<gnome-ui-info>} structures are
defined and then the appropriate functions from this module are called to create
the menu or tool bars.

@section Usage
@include defuns-gnome-app-helper.xml.texi

@c %end of fragment
