
@c %start of fragment

@node gnome-gconf
@chapter gnome-gconf
Provides access to the gconf module.

@section Overview
The gconf module provides a means for storing configuration parameters in a
directory-like structure. This module supplies a couple of convenience wrappers
for the most common ways an application will use gconf.

@section Usage
@include defuns-gnome-gconf.xml.texi

@c %end of fragment
