
@c %start of fragment

@node Layout Objects
@chapter Layout Objects
High-level layout driver objects

@section Overview
While complete access to the layout capabilities of Pango is provided using the
detailed interfaces for itemization and shaping, using that functionality
directly involves writing a fairly large amount of code. The objects and
functions in this section provide a high-level driver for formatting entire
paragraphs of text at once.

@section Usage
@include defuns-layout.xml.texi

@c %end of fragment
