
@c %start of fragment

@node Fonts
@chapter Fonts
Structures representing abstract fonts

@section Overview
Pango supports a flexible architecture where a particular rendering architecture
can supply an implementation of fonts. The @code{<pango-font>} structure
represents an abstract rendering-system-independent font. Pango provides
routines to list available fonts, and to load a font of a given description.

@section Usage
@include defuns-fonts.xml.texi

@c %end of fragment
