
@c %start of fragment

@node Unicode Manipulation
@chapter Unicode Manipulation
functions operating on Unicode characters and UTF-8 strings.

@section Overview
This section describes a number of functions for dealing with Unicode characters
and strings. There are analogues of the traditional @file{ctype.h} character
classification and case conversion functions, UTF-8 analogues of some string
utility functions, functions to perform normalization, case conversion and
collation on UTF-8 strings and finally functions to convert between the UTF-8,
UTF-16 and UCS-4 encodings of Unicode.

The implementations of the Unicode functions in GLib are based on the Unicode
Character Data tables, which are available from
@uref{http://www.unicode.org,www.unicode.org}. GLib 2.8 supports Unicode 4.0,
GLib 2.10 supports Unicode 4.1, GLib 2.12 supports Unicode 5.0.

@section Usage
@include defuns-unicode.xml.texi

@c %end of fragment
