#!/bin/sh

root=`dirname $0`/..
avail_packages=""
while read line; do
    if echo $line | egrep -q '^(#.*|[[:space:]]*)$'; then
        continue
    elif echo $line | egrep -qv '^[[:space:]]*[[:alnum:]_-]+:.*$'; then
        echo "Warning: bad PACKAGES statement: $line">&2
        continue
    fi
    package=`echo $line|sed -re 's/^[[:space:]]*([[:alnum:]_-]+):.*$/\\1/'`
    avail_packages="$avail_packages $package"
done < $root/PACKAGES

if test -z "$1" -o -n "$2"; then
    echo "usage: $0 PACKAGE"
    echo
    echo "available packages:$avail_packages"
    echo
    exit 1
fi

package=$1
echo "configuring $root as package $package"
subpackages=`grep $package: $root/PACKAGES|sed -re 's/^[^:]*:(.*)$/\\1/'`

branch_suffix=$3

for package in $subpackages; do
    if test -d $root/$package; then
        echo "warning, directory $root/$package already exists, not checking out $package"
    else
        echo "checking out $package"
        if git branch | grep -v -q $package; then
            echo "first checking out local tracking branch for origin/$package"
            git branch $package origin/$package
        fi
        git clone . $package
        ( cd $package; git checkout -b $package origin/$package )
    fi
done
