#!/bin/sh

root=`cd $(dirname $0)/.. && pwd`

echo "$root: git pull $@"
( cd $root; git pull "$@" )

for dir in $root/*; do
    if test -d $dir -a -d $dir/.git; then
        package=`basename $dir`
        echo "$root/$package: git pull $@"
        ( cd $dir; git pull "$@" )
    fi
done
