
@c %start of fragment

@node GtkTipsQuery
@chapter GtkTipsQuery
Displays help about widgets in the user interface

@section Overview
The @code{<gtk-tips-query>} widget is a subclass of @code{<gtk-label>} which is
used to display help about widgets in a user interface.

A query is started with a call to @code{gtk-tips-query-start-query}, usually
when some kind of 'Help' button is pressed. The @code{<gtk-tips-query>} then
grabs all events, stopping the user interface from functioning normally. Then as
the user moves the mouse over the widgets, the @code{<gtk-tips-query>} displays
each widget's tooltip text.

By connecting to the "widget-entered" or "widget-selected" signals, it is
possible to customize the @code{<gtk-tips-query>} to perform other actions when
widgets are entered or selected. For example, a help browser could be opened
with documentation on the widget selected.

At some point a call to @code{gtk-tips-query-stop-query} must be made in order
to stop the query and return the interface to its normal state. The
@code{gtk-tips-query-set-caller} function can be used to specify a widget which
the user can select to stop the query (often the same button used to start the
query).

@section Usage
@include defuns-gtktipsquery.xml.texi

@c %end of fragment
