
@c %start of fragment

@node GtkHBox
@chapter GtkHBox
A horizontal container box

@section Overview
GtkHBox is a container that organizes child widgets into a single row.

Use the @code{<gtk-box>} packing interface to determine the arrangement,
spacing, width, and alignment of GtkHBox children.

All children are allocated the same height.

@section Usage
@include defuns-gtkhbox.xml.texi

@c %end of fragment
