
@c %start of fragment

@node GtkListItem
@chapter GtkListItem
An item in a GtkList

@section Overview
The @code{<gtk-list-item>} widget is used for each item in a @code{<gtk-list>}.

GtkList has has been deprecated since GTK+ 2.0 and should not be used in newly
written code. Use @code{<gtk-tree-view>} instead.

@section Usage
@include defuns-gtklistitem.xml.texi

@c %end of fragment
