
@c %start of fragment

@node GtkPrinter
@chapter GtkPrinter
Represents a printer

@section Overview
A @code{<gtk-printer>} object represents a printer. You only need to deal
directly with printers if you use the non-portable
@code{<gtk-print-unix-dialog>} API.

A @code{<gtk-printer>} allows to get status information about the printer, such
as its description, its location, the number of queued jobs, etc. Most
importantly, a @code{<gtk-printer>} object can be used to create a
@code{<gtk-print-job>} object, which lets you print to the printer.

Printing support was added in GTK+ 2.10.

@section Usage
@include defuns-gtkprinter.xml.texi

@c %end of fragment
