
@c %start of fragment

@node GtkCellLayout
@chapter GtkCellLayout
An interface for packing cells

@section Overview
@code{<gtk-cell-layout>} is an interface to be implemented by all objects which
want to provide a @code{<gtk-tree-view-column-like>} API for packing cells,
setting attributes and data funcs.

One of the notable features provided by implementations of GtkCellLayout are
@emph{attributes}. Attributes let you set the properties in flexible ways. They
can just be set to constant values like regular properties. But they can also be
mapped to a column of the underlying tree model with
@code{gtk-cell-layout-set-attributes}, which means that the value of the
attribute can change from cell to cell as they are rendered by the cell
renderer. Finally, it is possible to specify a function with
@code{gtk-cell-layout-set-cell-data-func} that is called to determine the value
of the attribute for each cell that is rendered.

@section Usage
@include defuns-gtkcelllayout.xml.texi

@c %end of fragment
