
@c %start of fragment

@node GtkList
@chapter GtkList
Widget for packing a list of selectable items

@section Overview
The @code{<gtk-list>} widget is a container whose children are displayed
vertically in order, and can be selected. The list has many selection modes,
which are programmer selective and depend on how many elements are able to be
selected at the same time.

GtkList has been deprecated since GTK+ 2.0 and should not be used in newly
written code. Use @code{<gtk-tree-view>} instead.

@section Usage
@include defuns-gtklist.xml.texi

@c %end of fragment
