
@c %start of fragment

@node GtkPageSetupUnixDialog
@chapter GtkPageSetupUnixDialog
A page setup dialog

@section Overview
GtkPageSetupUnixDialog implements a page setup dialog for platforms which don't
provide a native page setup dialog, like Unix. It can be used very much like any
other GTK+ dialog, at the cost of the portability offered by the high-level
printing API

Printing support was added in GTK+ 2.10.

@section Usage
@include defuns-gtkpagesetupunixdialog.xml.texi

@c %end of fragment
