
@c %start of fragment

@node GtkPrintJob
@chapter GtkPrintJob
Represents a print job

@section Overview
A @code{<gtk-print-job>} object represents a job that is sent to a printer. You
only need to deal directly with print jobs if you use the non-portable
@code{<gtk-print-unix-dialog>} API.

Use @code{gtk-print-job-get-surface} to obtain the cairo surface onto which the
pages must be drawn. Use @code{gtk-print-job-send} to send the finished job to
the printer. If you don't use cairo @code{<gtk-print-job>} also supports
printing of manually generated postscript, via
@code{gtk-print-job-set-source-file}.

Printing support was added in GTK+ 2.10.

@section Usage
@include defuns-gtkprintjob.xml.texi

@c %end of fragment
