
@c %start of fragment

@node GtkCList
@chapter GtkCList
A multi-columned scrolling list widget

@section Overview
The @code{<gtk-clist>} widget is a very useful multi-columned scrolling list. It
can display data in nicely aligned vertical columns, with titles at the top of
the list.

GtkCList has been deprecated since GTK+ 2.0 and should not be used in newly
written code. Use @code{<gtk-tree-view>} instead.

@section Usage
@include defuns-gtkclist.xml.texi

@c %end of fragment
