
@c %start of fragment

@node GtkEventBox
@chapter GtkEventBox
A widget used to catch events for widgets which do not have their own window

@section Overview
The @code{<gtk-event-box>} widget is a subclass of @code{<gtk-bin>} which also
has its own window. It is useful since it allows you to catch events for widgets
which do not have their own window.

@section Usage
@include defuns-gtkeventbox.xml.texi

@c %end of fragment
