
@c %start of fragment

@node GtkTreeModelFilter
@chapter GtkTreeModelFilter
A GtkTreeModel which hides parts of an underlying tree model

@section Overview
A @code{<gtk-tree-model-filter>} is a tree model which wraps another tree model,
and can do the following things:

Filter specific rows, based on data from a "visible column", a column storing
booleans indicating whether the row should be filtered or not, or based on the
return value of a "visible function", which gets a model, iter and user_data and
returns a boolean indicating whether the row should be filtered or not.

Modify the "appearance" of the model, using a modify function. This is extremely
powerful and allows for just changing some values and also for creating a
completely different model based on the given child model.

Set a different root node, also known as a "virtual root". You can pass in a
@code{<gtk-tree-path>} indicating the root node for the filter at construction
time.

@section Usage
@include defuns-gtktreemodelfilter.xml.texi

@c %end of fragment
