
@c %start of fragment

@node GtkHButtonBox
@chapter GtkHButtonBox
A container for arranging buttons horizontally

@section Overview
A button box should be used to provide a consistent layout of buttons throughout
your application. The layout/spacing can be altered by the programmer, or if
desired, by the user to alter the 'feel' of a program to a small degree.

A @code{<gtk-hbutton-box>} is created with @code{gtk-hbutton-box-new}. Buttons
are packed into a button box the same way widgets are added to any other
container, using @code{gtk-container-add}. You can also use
@code{gtk-box-pack-start} or @code{gtk-box-pack-end}, but for button boxes both
these functions work just like @code{gtk-container-add}, ie., they pack the
button in a way that depends on the current layout style and on whether the
button has had @code{gtk-button-box-set-child-secondary} called on it.

The spacing between buttons can be set with @code{gtk-box-set-spacing}. The
arrangement and layout of the buttons can be changed with
@code{gtk-button-box-set-layout}.

@section Usage
@include defuns-gtkhbbox.xml.texi

@c %end of fragment
