
@c %start of fragment

@node GtkNotebook
@chapter GtkNotebook
A tabbed notebook container

@section Overview
The @code{<gtk-notebook>} widget is a @code{<gtk-container>} whose children are
pages that can be switched between using tab labels along one edge.

There are many configuration options for @code{<gtk-notebook>}. Among other
things, you can choose on which edge the tabs appear (see
@code{gtk-notebook-set-tab-pos}), whether, if there are too many tabs to fit the
noteobook should be made bigger or scrolling arrows added (see
gtk_notebook_set_scrollable), and whether there will be a popup menu allowing
the users to switch pages. (see @code{gtk-notebook-enable-popup},
@code{gtk-noteobook-disable-popup})

@section Usage
@include defuns-gtknotebook.xml.texi

@c %end of fragment
