
@c %start of fragment

@node GtkMisc
@chapter GtkMisc
Base class for widgets with alignments and padding

@section Overview
The @code{<gtk-misc>} widget is an abstract widget which is not useful itself,
but is used to derive subclasses which have alignment and padding attributes.

The horizontal and vertical padding attributes allows extra space to be added
around the widget.

The horizontal and vertical alignment attributes enable the widget to be
positioned within its allocated area. Note that if the widget is added to a
container in such a way that it expands automatically to fill its allocated
area, the alignment settings will not alter the widgets position.

@section Usage
@include defuns-gtkmisc.xml.texi

@c %end of fragment
