
@c %start of fragment

@node GtkFileChooserWidget
@chapter GtkFileChooserWidget
File chooser widget that can be embedded in other widgets

@section Overview
@code{<gtk-file-chooser-widget>} is a widget suitable for selecting files. It is
the main building block of a @code{<gtk-file-chooser-dialog>}. Most applications
will only need to use the latter; you can use @code{<gtk-file-chooser-widget>}
as part of a larger window if you have special needs.

Note that @code{<gtk-file-chooser-widget>} does not have any methods of its own.
Instead, you should use the functions that work on a @code{<gtk-file-chooser>}.

@section Usage
@include defuns-gtkfilechooserwidget.xml.texi

@c %end of fragment
