
@c %start of fragment

@node GtkCurve
@chapter GtkCurve
Allows direct editing of a curve

@section Overview
This widget is considered too specialized/little-used for GTK+, and will in the
future be moved to some other package. If your application needs this widget,
feel free to use it, as the widget does work and is useful in some applications;
it's just not of general interest. However, we are not accepting new features
for the widget, and it will eventually move out of the GTK+ distribution.

The @code{<gtk-curve>} widget allows the user to edit a curve covering a range
of values. It is typically used to fine-tune color balances in graphics
applications like the Gimp.

The @code{<gtk-curve>} widget has 3 modes of operation - spline, linear and
free. In spline mode the user places points on the curve which are automatically
connected together into a smooth curve. In linear mode the user places points on
the curve which are connected by straight lines. In free mode the user can draw
the points of the curve freely, and they are not connected at all.

@section Usage
@include defuns-gtkcurve.xml.texi

@c %end of fragment
