
@c %start of fragment

@node GtkTreeSortable
@chapter GtkTreeSortable
The interface for sortable models used by GtkTreeView

@section Overview
@code{<gtk-tree-sortable>} is an interface to be implemented by tree models
which support sorting. The @code{<gtk-tree-view>} uses the methods provided by
this interface to sort the model.

@section Usage
@include defuns-gtktreesortable.xml.texi

@c %end of fragment
