
@c %start of fragment

@node GtkCellRendererAccel
@chapter GtkCellRendererAccel
Renders a keyboard accelerator in a cell

@section Overview
@code{<gtk-cell-renderer-accel>} displays a keyboard accelerator (i.e. a key
combination like <Control>-a). If the cell renderer is editable, the accelerator
can be changed by simply typing the new combination.

The @code{<gtk-cell-renderer-accel>} cell renderer was added in GTK+ 2.10.

@section Usage
@include defuns-gtkcellrendereraccel.xml.texi

@c %end of fragment
