
@c %start of fragment

@node GtkAboutDialog
@chapter GtkAboutDialog
Display information about an application

@section Overview
The @code{<gtk-about-dialog>} offers a simple way to display information about a
program like its logo, name, copyright, website and license. It is also possible
to give credits to the authors, documenters, translators and artists who have
worked on the program. An about dialog is typically opened when the user selects
the @samp{About} option from the @samp{Help} menu. All parts of the dialog are
optional.

About dialog often contain links and email addresses. @code{<gtk-about-dialog>}
supports this by offering global hooks, which are called when the user clicks on
a link or email address, see @code{gtk-about-dialog-set-email-hook} and
@code{gtk-about-dialog-set-url-hook}. Email addresses in the authors,
documenters and artists properties are recognized by looking for
@samp{<user@@host>}, URLs are recognized by looking for @samp{http://url}, with
@samp{url} extending to the next space, tab or line break.

To make constructing a @code{<gtk-about-dialog>} as convenient as possible, you
can use the function @code{gtk-show-about-dialog} which constructs and shows a
dialog and keeps it around so that it can be shown again.

@section Usage
@include defuns-gtkaboutdialog.xml.texi

@c %end of fragment
