
@c %start of fragment

@node Drag and Drop
@chapter Drag and Drop
Functions for controlling drag and drop handling

@section Overview
GTK+ has a rich set of functions for doing inter-process communication via the
drag-and-drop metaphor. GTK+ can do drag-and-drop (DND) via multiple protocols.
The currently supported protocols are the Xdnd and Motif protocols. As well as
the functions listed here, applications may need to use some facilities provided
for Selections. Also, the Drag and Drop API makes use of signals in the
@code{<gtk-widget>} class.

@section Usage
@include defuns-gtkdnd.xml.texi

@c %end of fragment
