
@c %start of fragment

@node GtkImageMenuItem
@chapter GtkImageMenuItem
A menu item with an icon

@section Overview
A GtkImageMenuItem is a menu item which has an icon next to the text label.

Note that the user can disable display of menu icons, so make sure to still fill
in the text label.

@section Usage
@include defuns-gtkimagemenuitem.xml.texi

@c %end of fragment
