
@c %start of fragment

@node GtkEntry
@chapter GtkEntry
A single line text entry field

@section Overview
The @code{<gtk-entry>} widget is a single line text entry widget. A fairly large
set of key bindings are supported by default. If the entered text is longer than
the allocation of the widget, the widget will scroll so that the cursor position
is visible.

@section Usage
@include defuns-gtkentry.xml.texi

@c %end of fragment
