
@c %start of fragment

@node GtkPaperSize
@chapter GtkPaperSize
Support for named paper sizes

@section Overview
GtkPaperSize handles paper sizes. It uses the standard called "PWG 5101.1-2002
PWG: Standard for Media Standardized Names" to name the paper sizes (and to get
the data for the page sizes). In addition to standard paper sizes, GtkPaperSize
allows to construct custom paper sizes with arbitrary dimensions.

The @code{<gtk-paper-size>} object stores not only the dimensions (width and
height) of a paper size and its name, it also provides default print margins.

Printing support has been added in GTK+ 2.10.

@section Usage
@include defuns-gtkpapersize.xml.texi

@c %end of fragment
